### ISSUE TITLE
Cannot install rally app builder on windows 64 bit

### ISSUE THREAD

**Issue by pranav-shah** [RallyApps/rally-app-builder#17]
after using npm install -g rally-app-builder 
or the local install

get error Visual Studio 2005 and .net framework required..

after installing the above two s/w, get error no file found named:winsock2.h

![error rally](https://f.cloud.github.com/assets/4673053/638888/cfdb9da6-d2c7-11e2-8446-1512ae2d2de9.png)

**Comment by sathishsuresh2000** [comment]
Hi, I am not abled to npm install rally-app-builder in MAC. getting dependencies error(eg. error: No compatible version found: shelljs@'^0.3.0  ) .Please help it out. Can you please drop here the working node_module of rally-app-builder. Or can you tell me any versions that will successfully npm install rally-app-builder. I am struggling and strucked for past 2 weeks. Please help it out...
