### ISSUE TITLE
Unable to include fully qualified css files

### ISSUE THREAD

**Issue by krmorse** [RallyApps/rally-app-builder#35]

**Comment by ssteffl** [comment]
it would be nice to be able to have <link> tags for external stylesheets

**Comment by ssteffl** [comment]
sorry, github stripped the link tag from my post, it should read:
it would be nice to be able to have link tags for external stylesheets

**Comment by krmorse** [comment]
the original issue was meant to support including things like "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" in the css: [] section in the config.json file.  would this solve your use case?

**Comment by ssteffl** [comment]
yes that solves my problem

**Comment by krmorse** [comment]
cool.  i have it working locally, just need to finish the tests.  i'll get a new version published out to npm tomorrow hopefully.

**Comment by ssteffl** [comment]
awesome, thanks!

**Comment by krmorse** [comment]
fixed as of version 1.0.2.  let me know if it works for you?

**Comment by ssteffl** [comment]
yeah works as expected, thanks!
