### ISSUE TITLE
rab run doesn't work on windows

### ISSUE THREAD

**Issue by krmorse** [RallyApps/rally-app-builder#40]

**Comment by Clarity-Api** [comment]
It seems it is still not working. I am trying for last 3 hours, but no luck.

**Comment by krmorse** [comment]
It may be related to having spaces in your path name.  Does it work for you if you use it in a simple directory like C:\MyApp?

**Comment by krmorse** [comment]
I'm going to investigate changing out the lib that launches the browser and starts the local http server to see if that helps.

**Comment by krmorse** [comment]
In the meantime, do you have any error output you could send along to help diagnose?

**Comment by Clarity-Api** [comment]
Global didn't work, but finally able to setup using 
npm install rally-app-builder

Hurray, my first Rally app is ready.. Thanks for the prompt response.

**Comment by krmorse** [comment]
Awesome.  Have fun hacking!
