### ISSUE TITLE
Expose/Allow alteration of template for html generation (request)

### ISSUE THREAD

**Issue by jmartin-rally** [RallyApps/rally-app-builder#47]
It would be cool if we could provide an alternate template file while building for saving into source control with our project.  It'd be nice to be able to put something into the HTML or the basic setup of the page in a template so we don't have to do it by hand after the build.  The current use case (but there are others) is an instance where the developer wants to put extra html into the header like this:

<![if !IE]>
<script type="text/javascript" src="/apps/2.0rc3/sdk.js"></script>
<![endif]>

before the rally script tag.  (I can think of other instances where we might want to muck with the definition of the launch js or do something in the body.)  An alternate template would be awesome because we could version control it and we wouldn't have to keep remembering to add the stuff by hand on every build.

**Comment by krmorse** [comment]
working on this now...  stay tuned!

**Comment by krmorse** [comment]
Implemented in 1.2.5

You can specify templates to use either with the -t or --templates flags when running build/watch or just specify your templates in the config.json file
