### ISSUE TITLE
can't npm install with iojs 2.2.1

### ISSUE THREAD

**Issue by ssteffl** [RallyApps/rally-app-builder#48]
I dont' know if this is due to using iojs, but `npm install -g rally-app-builder` fails unless I manually install the following packages first:

    npm install -g brace-expansion
    npm install -g wrappy
    npm install -g concat-map
    npm install -g balanced-match
    npm install -g core-util-is

Only after i install those 5 dependencies globally can I install and rab build

**Comment by krmorse** [comment]
I'll try to look into this a bit.  I haven't used io.js yet.  I heard that it's going to be merging back with the main node project at some point in the future too, so that will be interesting.  Does this issue still happen with the latest release (3.3.1)?

**Comment by krmorse** [comment]
Wow, node has all come a long way since I last looked into it...  I just did a test with version 4.1.2 and it installed globally without issues (on OSX).  What platform are you using?

**Comment by ssteffl** [comment]
I honestly don't remember. That was a long time ago. I haven't run into it in awhile so ill close this.
