### ISSUE TITLE
Default template source file points to a resource location that does not exist.

### ISSUE THREAD

**Issue by Ciaraf** [RallyApps/rally-app-builder#49]
I created a new app with  rally-app-builder.
```
C:\Users\cfinan\Desktop\SecondApp>rally-app-builder init secondApp
Creating a new App named secondApp
Creating App-debug.html
Creating App.html
Creating App-external.html
Creating App-uncompressed.html
Success
```
Then, did `rally-app-builder run` command.

The page opens in the browser and tries to load a script that does not exist. From the console , the error reads:
 Failed to load resource: the server responded with a status of 404 (Not Found) https://rally1.rallydev.com/apps/World/sdk-debug.js

I haven't modified anything else in the project. This is the default link.

**Comment by Ciaraf** [comment]
This issue was solved by updating rally-app-builder to its newest version.

**Comment by krmorse** [comment]
great, glad you got it.
