### ISSUE TITLE
not working on node version 5.10

### ISSUE THREAD

**Issue by ssteffl** [RallyApps/rally-app-builder#55]
rab does nothing on node version 5.10, and doesn't produce even an error message. 

![rab-not-working-v5](https://cloud.githubusercontent.com/assets/7218524/14511517/f31dc93c-01a5-11e6-96fa-ee6499ea4a42.PNG)

**Comment by krmorse** [comment]
I refactored the command line arg parsing code in the latest release and as part of that removed the default build behavior if no arguments were passed.  If you do a regular rab build does it still work?

**Comment by ssteffl** [comment]
ok thanks. rab build works
