### ISSUE TITLE
not able to install on windows

### ISSUE THREAD

**Issue by Qijiang60** [RallyApps/rally-app-builder#64]
Hi, I am not able to npm install rally-app-builder in Windows. Error as below:
Refusing to install rally-app-builder as a dependency of itself.

Please advises......

**Comment by krmorse** [comment]
Interesting...  I haven't seen other reports of this, but I'll investigate.  Stay tuned...

**Comment by krmorse** [comment]
I was able to install it just fine on both windows 10 and windows 7 using node 6.  What Windows/node versions are you using?  Are you installing it globally or locally?

**Comment by Qijiang60** [comment]
My side is Windows 7, node 6 Locally installing.

**Comment by krmorse** [comment]
I just published v1.5.1 which updated a bunch of dependencies and should help specifically on Windows 10 and newer node versions.  Would you mind giving it a try?
