### ISSUE TITLE
can NOT install on Windows 10 

### ISSUE THREAD

**Issue by leowins** [RallyApps/rally-app-builder#66]
Hi could someone please help?
@krmorse

It can NOT install on Windows 10.   
Details please refer to the attached npm-debug.log

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'c:\package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "rally-app-builder"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\npm-debug.log

**Comment by leowins** [comment]
npm-debug.log attached. 
[npm-debug.log.txt](https://github.com/RallyApps/rally-app-builder/files/723909/npm-debug.log.txt)

**Comment by dsaner** [comment]
I'm having a similar issue on win 10.  node version 6.9.4.  Several warnings before I hit this SKIPPING OPTIONAL DEPENDENCY:

npm WARN deprecated wrench@1.3.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated graceful-fs@1.1.14: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\dsaner\AppData\Roaming\npm\rab -> C:\Users\dsaner\AppData\Roaming\npm\node_modules\rally-app-builder\bin\rally-app-builder
C:\Users\dsaner\AppData\Roaming\npm\rally-app-builder -> C:\Users\dsaner\AppData\Roaming\npm\node_modules\rally-app-builder\bin\rally-app-builder
C:\Users\dsaner\AppData\Roaming\npm
`-- rally-app-builder@1.4.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\rally-app-builder\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})



It does appear to install, but when I attempt to build an app, I get the following errors:

rally-app-builder build
Compiling the App.
fs.js:101
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: EPERM: operation not permitted, open 'C:\P4SCC\QAAutomation\Projects\Main\Rally\RallyTestCoverageByIteration\config.json'
    at Error (native)



Any guidance would be greatly appreciated!

**Comment by krmorse** [comment]
I'm investigating.  I think most of those super outdated dependencies are only used for the clone command anyway, which I've been considering getting rid of for some time.  Thanks for reporting these issues!

**Comment by leowins** [comment]
I figured out a way to fix my own installation issue for rally-app-builder. 
I ran into 3 issues. 
1. 
42069 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
42070 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

to resolve it, I used:
npm install --no-optional rally-app-builder

**Comment by leowins** [comment]
2. 
npm ERR! Refusing to install package with name "rally-app-builder" under a package
npm ERR! also called "rally-app-builder". Did you name your project the same
npm ERR! as the dependency you're installing?

to resolve it, I changed the name in package.json file from  "rally-app-builder" to " "rally-app-builder-test"

**Comment by leowins** [comment]
3. 
Phantom installation failed { Error: EPERM: operation not permitted, unlink 'C:\Users\leo\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1485397694143\phantomjs-1.9.8-windows\phantomjs.exe'
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\leo\\AppData\\Local\\Temp\\phantomjs\\phantomjs-1.9.8-windows.zip-extract-1485397694143\\phantomjs-1.9.8-windows\\phantomjs.exe' } Error: EPERM: operation not permitted, unlink 'C:\Users\leo\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1485397694143\phantomjs-1.9.8-windows\phantomjs.exe'
rally-app-builder@1.4.1 c:\github
`-- (empty)

to resolve it, I disabled anti-virus software protection, then run 
npm cache clean

now rally-app-builder seemed to installed successfully.

NOT SURE WHETHER rally-app-builder actually will work after installation... will test it out...

**Comment by leowins** [comment]
Not sure why I had to do the above 3 steps and the rational behind them.
could anyone @krmorse explain?

**Comment by leowins** [comment]
Just tested it out -> does NOT seem to work... will look into it.

c:\github\rally-app-builder>rally-app-builder init BasicRallyGrid
module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\leo\AppData\Roaming\npm\node_modules\rally-app-builder\bin\rally-app-builder'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

**Comment by leowins** [comment]
Reason is there is no rally-app-builder folder under path:
C:\Users\leo\AppData\Roaming\npm\node_modules\ 

I had to cd into rally-app-builder folder first, otherwise "rally-app-builder" command is not found

**Comment by krmorse** [comment]
@leowins, the most common usage is to install rally-app-builder globally (using the -g flag when running npm install).  that way you can execute it from anywhere as long as node is correctly on your path.  If executing it from a local npm install you probably need to do ./bin/rally-app-builder init BasicRallyGrid

**Comment by krmorse** [comment]
@leowins, @dsaner, I just published version 1.5.1 which updated a bunch of dependencies and I think that should resolve the issues on Windows 10 and newer node versions.  Would you try it out and see if it works for you now?

**Comment by krmorse** [comment]
shoot, try again @dsaner ?

**Comment by dsaner** [comment]
got it that time.  Install looked cleaner too.  Was able to successfully build my app.  Thanks!
