### ISSUE TITLE
Sometimes Config files are deleted

### ISSUE THREAD

**Issue by ferentchak** [RallyApps/rally-app-builder#74]
I think it's due to errors occurring during the reformatting portion of getting the config.

**Comment by krmorse** [comment]
i've seen that happen too.  never got to the bottom of it, but assumed it was exploding silently

**Comment by ferentchak** [comment]
It frustrates the guys here. When I put that code in the purpose was to pretty print their config for them. Now there is so much tooling its probably more annoying than anything.

**Comment by krmorse** [comment]
Fixed in 1.6.2
