### ISSUE TITLE
Unable to install rally-app-builder

### ISSUE THREAD

**Issue by pratik73** [RallyApps/rally-app-builder#87]
Hi,
I am trying to install the rally-app-builder, and it is throwing an error for phantomjs.
my node version is : 8.9.4
npm version : 5.8.0

Error : Failed at the phaontomjs-prebuilt@2.1.16 install script

is there a way to get around this in case phantom is not mandatory.

**Comment by krmorse** [comment]
what os? windows?  i was able to successfully install it on my macbook, same node/npm versions...

**Comment by pratik73** [comment]
I think it is because of some restriction in my office network. installed fine in my personal laptop.
thanks.
